// angular/angular-app/src/app/container1/container1.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';

@Component({
  selector: 'app-container1',
  templateUrl: './container1.component.html',
  styleUrls: ['./container1.component.css']
})
export class Container1Component implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  @ViewChild('tekst1', {static: true}) tekst1: any
  @ViewChild('tekst2', {static: true}) tekst2: any
  @ViewChild('asyncTime', {static: true}) asyncTime: any

  async textDisplay1() {

    var t = performance.now()
    var txt2 = await this.textDisplay2()
    
    this.tekst1.nativeElement.style.display = "block"
    this.tekst2.nativeElement.style.display = txt2
    
    var time = performance.now() - t + 'milisekund'
    this.asyncTime.nativeElement.innerHTML = time
  }

  textDisplay2() {
    return new Promise(resolve => setTimeout(() => { resolve('block') }, 0))
  }
}

<div id="container1" class="cont">
    <h1>Procesy asynchroniczne</h1><br>
    <button (click)="textDisplay1()">Asynchroniczność</button>

    <div id="tekst1" style="display: none" #tekst1>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius dictum metus quis aliquet. Cras ac convallis nisl, venenatis</div>
    <br><br>
    <div id="tekst2" style="display: none" #tekst2>ngilla enim vulputate. Nulla facilisi. Aliquam erat volutpat. Morbi ut lacus ac nisi efficitur tristique. Quisque inte</div>
    <div id="asyncTime" #asyncTime></div><br>
    
</div>
<a href="#container2">
    <div class="arrow">
        <p class="arrow-para">V</p>
    </div>
</a>

// vue/vue-cli/Vue-CLI/src/components/Container1.vue
<template>
  <div>
    <div id="container1" class="cont">
      <h1>Procesy asynchroniczne</h1>
      <br />
      <button v-on:click="textDisplay1">Asynchroniczność</button>
      <div
        id="tekst1"
        style="display: none"
      >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius dictum metus quis aliquet. Cras ac convallis nisl, venenatis</div>
      <br />
      <br />
      <div
        id="tekst2"
        style="display: none"
      >ngilla enim vulputate. Nulla facilisi. Aliquam erat volutpat. Morbi ut lacus ac nisi efficitur tristique. Quisque inte</div>
      <div id="asyncTime"></div>
      <br />
    </div>
    <div>
      <a href="#container2">
        <div class="arrow">
          <p class="arrow-para">V</p>
        </div>
      </a>
    </div>
  </div>
</template>

<script>

export default {
  name:'Container1',
  methods:{
    async textDisplay1(){
      var tekst2 = document.querySelector('#tekst2')
      var tekst1 = document.querySelector('#tekst1')
      var t = performance.now()
      var txt2 = await this.textDisplay2()

      tekst2.style.display = txt2
      tekst1.style.display = 'block'

      var time = performance.now() - t + 'milisekund'

      document.querySelector('#asyncTime').innerHTML = time

    },
    textDisplay2() {
        return new Promise(resolve => setTimeout(() => { resolve('block') }, 0))
    }
  }
}
</script>
