// vue/vue-app/src/components/Container4.vue
<template>
    <div>
        <div id="container4" class="cont"><h1>Animacje</h1>
            <div id="btns"><!--byl but-->
                <button class="slideButton" @click="Slide">Play</button>
            </div>
            <div class="box red"></div>
            <div class="box blue"></div>
            <div class="box lime"></div>
            <div class="box yellow"></div>
        <br><br><br><br>Czas trwania animacji
            <p id="animationTime"></p>
        </div>
        <div class="footer"></div>
    </div>
</template>

<script>
import anime from 'animejs'
var t1
var t2
export default {
  name: 'Container4',
  methods: {
    Slide() {
    var timeResolution = document.getElementById('animationTime')
      anime({
        targets: 'div.box',
        translateX: [
          { value: 200, duration: 500 },
          { value: 0, duration: 500 }
        ],
        rotate: {
          value: '1turn',
          easing: 'easeInOutSine'
        },
        borderRadius: ['0%', '50%'],
        easing: 'easeInOutQuad',
        opacity: '0.3',
        begin: function () {
          t1 = performance.now()
        },
        complete: function () {
          t2 = performance.now()
          timeResolution.innerHTML = t2 - t1 + ' milisekund'
        },
        delay: function (el, i) { return i * 1000 }
      })
    } 
  }
}
</script>

// angular/angular-app/src/app/container4/container4.component.ts
import { Component, ViewChild, AfterViewInit } from '@angular/core';
import anime from 'animejs/lib/anime.es';

//import * as anime from 'animejs';

@Component({
  selector: 'app-container4',
  templateUrl: './container4.component.html',
  styleUrls: ['./container4.component.css']
})

export class Container4Component implements AfterViewInit {

  constructor() { }

  t1: any;
  t2: any;
  Slide: any;
  time: any;

  ngAfterViewInit(): void {

    this.Slide = anime({
      targets: 'div.box',
      translateX: [
        { value: 200, duration: 500 },
        { value: 0, duration: 500 }
      ],
      rotate: {
        value: '1turn',
        easing: 'easeInOutSine'
      },
      borderRadius: ['0%', '50%'],
      easing: 'easeInOutQuad',
      opacity: '0.3',
      begin: function () {
        this.t1 = performance.now()
      },
      complete: function () {
        this.t2 = performance.now()
        this.time = this.t2 - this.t1 + ' milisekund'
        const timeResolution: HTMLElement = document.getElementById('animationTime') as HTMLElement
        timeResolution.innerHTML = this.time

      },

      delay: function (el, i: number) { return i * 1000 },
      autoplay: false,

    })

  }

  slideButton() {
    this.Slide.play()
  }

}

<div id="container4" class="cont"><h1>Animacje</h1>
    <div id="btns"><!--tu byl 'but' -->
        <button class="slideButton" #slideButton (click)='slideButton()'>Play</button>
    </div>
    <div class="box red"></div>
    <div class="box blue"></div>
    <div class="box lime"></div>
    <div class="box yellow"></div>
<br><br><br><br>Czas trwania animacji
    <p id="animationTime" #timeResolution></p>
</div>
