// vue/vue-cli/Vue-CLI/src/components/Container4.vue
<template>
    <div>
        <div id="container4" class="cont"><h1>Animacje</h1>
            <div id="btns"><!--byl but-->
                <button class="slideButton">Play</button>
            </div>
            <div class="box red"></div>
            <div class="box blue"></div>
            <div class="box lime"></div>
            <div class="box yellow"></div>
        <br><br><br><br>Czas trwania animacji
            <p id="animationTime"></p>
        </div>
        <div class="footer"></div>
    </div>
</template>

<script>
import anime from 'animejs'
var t1
var t2
var timeResolution = document.querySelector('#animationTime')
export default {
  name: 'Container4',
  methods: {
    Slide: anime({
      targets: 'div.box',
      translateX: [
        { value: 200, duration: 500 },
        { value: 0, duration: 500 }
      ],
      rotate: {
        value: '1turn',
        easing: 'easeInOutSine'
      },
      borderRadius: ['0%', '50%'],
      easing: 'easeInOutQuad',
      opacity: '0.3',
      begin: function () {
        t1 = performance.now()
      },
      complete: function () {
        t2 = performance.now()
        timeResolution.innerHTML = t2 - t1 + ' milisekund'
      },
      delay: function (el, i) { return i * 1000 },
      autoplay: false
    })
  }
}
document.querySelector('.slideButton').onclick = this.Slide.play
</script>

// angular/angular-app/src/app/container4/container4.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
declare var anime: any;
//import anime from 'animejs';


@Component({
  selector: 'app-container4',
  templateUrl: './container4.component.html',
  styleUrls: ['./container4.component.css']
})

export class Container4Component implements OnInit {

  constructor() { }

  t1:any;
  t2:any;
  @ViewChild('slideButton') slideButton: any
  @ViewChild('animationTime') timeResolution: any


  ngOnInit(): void {
  }

    
    Slide = anime({
      targets: 'div.box',
      translateX: [
        { value: 200, duration: 500 },
        { value: 0, duration: 500 }
      ],
      rotate: {
        value: '1turn',
        easing: 'easeInOutSine'
      },
      borderRadius: ['0%', '50%'],
      easing: 'easeInOutQuad',
      opacity: '0.3',
      begin: function () {
        this.t1 = performance.now()
      },
      complete: function () {
        this.t2 = performance.now()
        this.timeResolution.nativeElement.innerHTML = this.t2 - this.t1 + ' milisekund'
      },
      delay: function (el, i) { return i * 1000 },
      autoplay: false
    })

    //this.slideButton.addEventListener('click',this.Slide.play())
    //this.slideButton.nativeElement.onclick= Slide.play




}

<div id="container4" class="cont"><h1>Animacje</h1>
    <div id="btns"><!--tu byl 'but' -->
        <button class="slideButton" .slideButton (click)='slideButton()'>Play</button>
    </div>
    <div class="box red"></div>
    <div class="box blue"></div>
    <div class="box lime"></div>
    <div class="box yellow"></div>
<br><br><br><br>Czas trwania animacji
    <p id="animationTime" #timeResolution></p>
</div>
