// vue/vue-app/src/App.vue
<template>
  <div id="app">
    <Menu />
    <Home />
    <Container1 />
    <Container2 />
    <Container3 />
    <Container4 />
  </div>
</template>

<script>

import Menu from './components/Menu.vue'
import Home from './components/Home.vue'
import Container1 from './components/Container1'
import Container2 from './components/Container2'
import Container3 from './components/Container3'
import Container4 from './components/Container4'

export default {
  name: 'App',
  components: {
    Menu,
    Home,
    Container1,
    Container2,
    Container3,
    Container4
  }
}
</script>

<style lang="scss">
 @import './assets/style.css';
</style>

// react-app/src/App.js
import React, {Component} from "react"
import Menu from "./menu"
import Home from "./home"
import Arrow from "./arrow"
import Cont1 from "./container1"
import Cont2 from "./container2"
import Cont3 from "./container3"
import Cont4 from "./container4"

class App extends Component {
    render() {
        return (
            <div>
                <Menu />
                <Home />
                <Arrow anchor={'#container1'} />
                <Cont1 />
                <Arrow anchor={'#container2'} />
                <Cont2 />
                <Arrow anchor={'#container3'} />
                <Cont3 />
                <Arrow anchor={'#container4'} />
                <Cont4 />
                
            </div>
        )
    }
}

export default App
