// vue/vue-app/src/components/Container4.vue
<template>
    <div>
        <div id="container4" class="cont"><h1>Animacje</h1>
            <div id="btns">
                <button class="slideButton" @click="Slide">Play</button>
            </div>
            <div class="box red"></div>
            <div class="box blue"></div>
            <div class="box lime"></div>
            <div class="box yellow"></div>
        <br><br><br><br>Czas trwania animacji
            <p id="animationTime"></p>
        </div>
        <div class="footer"></div>
    </div>
</template>

<script>

import anime from 'animejs'
var t1
var t2

export default {
  name: 'Container4',
  methods: {
    Slide() {
    var timeResolution = document.getElementById('animationTime')
      anime({
        targets: 'div.box',
        translateX: [
          { value: 200, duration: 500 },
          { value: 0, duration: 500 }
        ],
        rotate: {
          value: '1turn',
          easing: 'easeInOutSine'
        },
        borderRadius: ['0%', '50%'],
        easing: 'easeInOutQuad',
        opacity: '0.3',
        begin: function () {
          t1 = performance.now()
        },
        complete: function () {
          t2 = performance.now()
          timeResolution.innerHTML = t2 - t1 + ' milisekund'
        },
        delay: function (el, i) { return i * 1000 }
      })
    } 
  }
}
</script>

// react-app/src/container4.js
import React, { Component } from 'react'
import { anime } from 'react-anime'

class Cont4 extends Component {

  constructor(props) {
    super(props)
    this.state = {
      t1: 0,
      t2: 0
    }
    this.handleOnClick = this.handleOnClick.bind(this);
  }

  handleOnClick() {

    var slide = anime.timeline()

      .add({
        begin: function () {
          this.t1 = performance.now()
          this.setState({ t1: this.t1 })
        }.bind(this),

        complete: function () {
          this.t2 = performance.now()
          this.setState({ t2: this.t2 })

          this.setState(() => {
            return { timeResolution: this.state.t2 - this.state.t1 + ' milisekund' }
          })
        }.bind(this),

        delay: (el, i) => i * 1000,
        targets: '.box',
        translateX: [
          { value: 200, duration: 500 },
          { value: 0, duration: 500 }
        ],
        rotate: {
          value: '1turn',
          easing: 'easeInOutSine'
        },
        borderRadius: ['0%', '50%'],
        easing: 'easeInOutQuad',
        opacity: '0.3'
      })
    slide.play()
  }


  render() {
    return (
      <div id="container4" className="cont"><h1>Animacje</h1>
        <div id="btns">
          <button className="slideButton" onClick={this.handleOnClick}>Play</button>
        </div>
        <div className="box red"></div>
        <div className="box blue"></div>
        <div className="box lime"></div>
        <div className="box yellow"></div>
        <br /><br /><br /><br />Czas trwania animacji
        <p id="animationTime">{this.state.timeResolution}</p>
      </div>
    )
  }
}

export default Cont4
