// react-app/src/container3.js
import React, { Component } from 'react'

class Cont3 extends Component {

    constructor(props) {
        super(props)
        this.time0 = null
        this.time1 = null
        this.state = {
            prob10: null,
            prob100: null,
            prob10000: null,
            wyniki: []
        }
        this.losuj = this.losuj.bind(this)
        this.sortNumber = this.sortNumber.bind(this)
        this.timePerformance = this.timePerformance.bind(this)
        this.formatowanie = this.formatowanie.bind(this)
        this.czasFormatowania = this.czasFormatowania.bind(this)
        this.createTable = this.createTable.bind(this)
    }

    losuj(rozmiar, zakres) {
        let tablica = []
        for (var i = 0; i < rozmiar; i++) {
            tablica.push(
                <li key={i} item={Math.floor(Math.random() * zakres)} />
            )
        }
        return tablica
    }

    sortNumber(a, b) {
        return a - b
    }

    timePerformance(rozmiarTablicy, zakresLiczbWTablicy, iloscPowtorzen) {
        var time = 0
        var liczby = []
        for (var j = 0; j < iloscPowtorzen; j++) {
            liczby = liczby.map(() => this.losuj(rozmiarTablicy, zakresLiczbWTablicy))
            time -= performance.now()
            liczby = liczby.sort(() => this.sortNumber())
            time += performance.now()
        }

        return time / iloscPowtorzen
    }

    componentDidMount() {
        this.setState({
            prob10: this.timePerformance(10, 100, 1000),
            prob100: this.timePerformance(100, 100, 1000),
            prob10000: this.timePerformance(10000, 100, 1000)
        })
    }


    formatowanie() {
        this.time0 = performance.now()
        var iloscPowtorzen = 10
        const domStyle = {
            border: '1px solid black'
        }
        let table = []
        for (var j = 0; j < iloscPowtorzen; j++) {
            table.push(<table style={domStyle}>
                {this.createTable()}
            </table>)
        }
        this.time1 = performance.now()
        return table
    }

    createTable() {
        var tabela
        let wyniki = [this.state.prob10, this.state.prob100, this.state.prob10000]
        tabela = (<tr>
            <td style={{ border: '1px solid black' }}>{wyniki[0]}</td>
            <td style={{ border: '1px solid black' }}>{wyniki[1]}</td>
            <td style={{ border: '1px solid black' }}>{wyniki[2]}</td>
        </tr>)

        return tabela
    }

    czasFormatowania() {
        return (
            <p id='czasFormatowania'>
                {this.time1 - this.time0 + ' milisekund'}
            </p>
        )
    }

    render() {
        return (
            <div id="container3" className="cont">
                <h1>Sortowanie i formatowanie </h1><br /><br />
                <h2>Sortowanie</h2>
                Sortowanie dla 3 różnych prób, powtórzone 1000 razy <br /><br /><br />
                <li>proba licząca 10 wylosowanych liczb w tablicy</li>
                <p id="prob10" className="prob">
                    {this.state.prob10}
                </p>
                <li>proba licząca 100 wylosowanych liczb w tablicy</li>
                <p id="prob100" className="prob">
                    {this.state.prob100}
                </p>
                <li>proba licząca 10000 wylosowanych liczb w tablicy</li>
                <p id="prob10000" className="prob">
                    {this.state.prob10000}
                </p>
                <br /><h2>Formatowanie</h2>
                <div id='formatowanie'>
                    {this.formatowanie()}
                </div>
                <br /><br />Czas formatowania tabeli <br /><br />
                <div id='czasFormatowania'>
                    {this.czasFormatowania()}
                </div>
            </div>
        )
    }
}

export default Cont3

// vue/vue-app/src/components/Container3.vue
<template>
    <div id="container3" class="cont">
        <h1>Sortowanie i formatowanie </h1><br><br>
        <h2>Sortowanie</h2>
        Sortowanie dla 3 różnych prób, powtórzone 1000 razy <br><br><br>
        <li>proba licząca 10 wylosowanych liczb w tablicy</li>
        <p id="prob10" class="prob"></p>
        <li>proba licząca 100 wylosowanych liczb w tablicy</li>
        <p id="prob100" class="prob"></p>
        <li>proba licząca 10000 wylosowanych liczb w tablicy</li>
        <p id="prob10000" class="prob"></p>
        <br><h2>Formatowanie</h2>
        <div id='formatowanie'></div>
        <br><br> Czas formatowania tabeli <br><br>
        <div id="czasFormatowania"></div>
        <a href="#container4">
            <div class="arrow">
                <p class="arrow-para">V</p>
            </div>
        </a>
    </div>
</template>

<script>

var wyniki

export default {
  name: 'Container3',
  methods: {
    losuj (rozmiar, zakres) {
      var los = []
      for (var i = 0; i < rozmiar; i++) {
        los.push(Math.floor(Math.random() * zakres))
      }
      return los
    },
    sortNumber (a, b) {
      return a - b
    },
    timePerformance (rozmiarTablicy, zakresLiczbWTablicy, iloscPowtorzen) {
      var time = 0
      var liczby = []
      for (var j = 0; j < iloscPowtorzen; j++) {
        liczby = this.losuj(rozmiarTablicy, zakresLiczbWTablicy)
        time -= performance.now()
        liczby.sort(this.sortNumber)
        time += performance.now()
      }
      return time / iloscPowtorzen
    },
    formatowanie () {
      var time0 = performance.now()
      var iloscPowtorzen = 10
      for (var j = 0; j < iloscPowtorzen; j++) {
        var table = document.createElement('table')
        table.style.border = '1px solid black'
        for (var i = 0; i < 3; i++) {
          var tr = table.insertRow()
          var td = tr.insertCell()
          td.appendChild(document.createTextNode(wyniki[i].innerText))
          td.style.border = '1px solid black'
        }
        document.getElementById('formatowanie').appendChild(table)
      }
      var time1 = performance.now()
      document.querySelector('#czasFormatowania').innerHTML = time1 - time0 + ' milisekund'
    }
  },
  mounted () {
    var prob10 = document.querySelector('#prob10')
    var prob100 = document.querySelector('#prob100')
    var prob10000 = document.querySelector('#prob10000')
    prob10.innerHTML = this.timePerformance(10, 100, 1000)
    prob100.innerHTML = this.timePerformance(100, 100, 1000)
    prob10000.innerHTML = this.timePerformance(10000, 100, 1000)
    wyniki = [prob10, prob100, prob10000]
    this.formatowanie()
  }
}
</script>
